spring:
    application:
        name: order
    datasource:
        url: jdbc:postgresql://localhost:5432/microservices_ss03_ex01_order
        username: postgres
        password: TuanDung@127
    jpa:
        hibernate:
            ddl-auto: update

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
server:
    port: 8082